<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Boor_porces" Id="{005434f7-2785-4bf5-9d10-f9d7f4874b40}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Boor_porces
VAR
	Step: UINT:=0; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Boor_porces">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>